language: node_js
node_js:
- '8'
dist: trusty
sudo: false
install:
- npm install
script:
- npm run code-check
- npm run build
- npm run test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: jb2wjP4M0FcpGTNz8DhD/leURIZMQ5hm8bAzKRPNs20kJloY0H2zJBFwo+gj8Pr07IY3k0Gt1jM0TXfk5CrOB5cJBVWsRBA+K4g0QNak2AFVFwQImkZ/w+ha06XMWCxbjRjoAq/L0xPDXMlKtfe366NCfCVTso6xK6W627LYnH2OhLvmsg0wzd0Nn0h66my50ozy/edY36VBnu4W0UL26KZQ3SDgXQNb0ggFbpHRAnE9rkdYPuGNf6z03IYgf6TSshBT5EvSZPxWCBOiYxVqdFLdopPwR31kZnuKvDieW6rXWgALsdt+JX4A65Mm/PEyOmuA/a+myunV/SKyrhwuk9FA/4gGZW5cWU9heXmFovbogHrtcKm9Rkoh2bWdsfcwOB7AWXdYON99WU+GDHHGSHASsc5Ot8ZS63ypK3d4oHgoFlPlzKp+wCsRhohX1asO2GjxBKRVufIUk78OgPB4gQ57QunkyJWgsVVk1R2LzEI8bZLVLpmACi9FxAtAfu9RqslGqSvy8GKBxvwGbNxSqVFJpsmqPHDsfh1YtXkmw7JmNChXm8j1l40Uv34/ulifDBpu7uXhPacRs0+SRNg+uGXTnj4ZAiaihj/E3kOB59Dyyb923LwrlEawpckKY8vW6rFSXVVE2KqfthS/kt1fofDcHTuHq43V8LlYZ6znysU=
  on:
    branch: master
env:
  global:
  - secure: UqidEwT1DkCfU4iDVMPdMI1nbtXqdaEyMM7xlKMfKruj2He10e4ThLFrLyCMAQ9yj5NtmZ7tlTkvzGxAZqB3BB43j3DGP2w18TzCncuSyJGQKylfT2hNf7KhmVkFhQor20eJB7I//4cRe5JQpmPaF3QQLEsX3X4Kv21Ge7DRTcHbDvgco5YclrBmbFkA2h1iHkrvMzcW1rFvfNjNkHOunbr0eJh6MmffV75MZgWcOIvM+fuelq48rYf941KAt6y2pYEOBUDh0kqtxnRXX5WRzbYjpQAfnBNtVXokcXddZC/6VDW1skATig6XI3ADwiQ6ZZBeV2SWZSZNJKtUtNcJWthzuEj1mSZxJac80lgUoX8N9bttZp+W4UfYfqnThah6XN5TDwusLqHYrx1smwN4FWs1FlUj243kjG+IkDTq1whcXarl1oX32FbTRpyRcZ+hZh+pmULEujeG6K6ijcgciFeRYQv1TzTzqom2DFVeeSRhkuN47Qli2h2tJhgPdg5g1ZgX97vejHoGMMZChgLvMkAWW1cjw+xy5WIeqgpSi1E+UzslQna1pbHrVkJJLMk5gFQEK5CDre547mD3/w/xfT9YGKB2T9DYBHeKI4mUQ56IQWTPOMra+DeXl0J6D+OAneoDXzC0izsENHzN5VXZSRm+HndlRw7hhbxcbl1BckI=
  - secure: KvZgbiPhSGKipjFb6SJtuhQJ69HSpn/EneU/6hrktvqrVyhVveise5nZsS106H5mvPNJXC0LiCTfRp0Cl19x56mU3FV6oRUWyunADuqNEP7dxOgYQDk83WXne7DIBEtQE6AyHg/ObcNzAn3kgEIBKykUwmnEqOU9xlQ6RLjafKTxXUhWiVo2xwzoSUZGSi4BFtR0+zSuwGJZ6uaSgAZHlBt+C17GmfVPsUXV0xrqM/ygWM1PcZYChUVvolSHLf1kFcquxHqRIBfs0j0SVlu3Vtev2+N+YStZnbGn5azpmT/Cm8N2iDN8YExLJVs1/gCdY0rRJ3fdDf4jxxtsNVYbXSSIKiEPAYbuqxNo+Gn4IlQhbt1oUIMPxGY0u5PZaezUwTyMrO3aW9UGj61b8n8HIQbKK90YN1yu+8bQtKgSjewPv2nOD/A3yQFjRxWqgzQbx3EEybxi+Fnl8e8jNipGGSlqn0T0BJ8CG4WYI93inBzxMAXNCDhGj9aD7qd7cTzpSSpm+fnmZTUDqYzlS+IAsZuqYUjfa+XvDs4gB0IzDH8ueIIpk4Jpf9sgEec1SLBKu5fv0H5/J1+OAlQsok1dg0MAkka54o7P9t+Grw8p2kYLAJLmf+dC/ef39uVJ7QRthnwvra1vZazfDO8Ytl9oP+3Az/RajmSn59h02XVUhTw=
