language: node_js
node_js:
- '8'
dist: trusty
sudo: false
install:
- npm install
script:
- npm run code-check
- npm run build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: vPQ+jv3Hhd2aOuqcU4Vh6hrJA/Jac/mbkBleI47d2jKj+eg5mPZBTa9XmkIQEKgquZW7yAOUE9fdeBsoJ4sv/O4bfv15eX8f+oVQZzyjRkdIUJBXOEBAcBOlVhNcjf8l7FWN3w3mCFlxBocnHUxM7l9UXu/9U3E+LP2DQ/PnRiKMlRsbhD70ZsdK3ysb+qD49bEj4uu0LZOzXg5rdmYWnlaQ3aVUtxtmaRa/YS1usEFCucFV8blin+bhgMsQa3seIdBBrlg68/TIZzV0dLCB/K/8eN9S8mUjQKNOoRWBingSha8d/V23oGAHj5m3TxkO2ZwLZPdVDrt2yM5vDy2Ol1xuWSTO7pxGUO4JrsWe7oX/b1skP062dLLgeDuNnF5tkYmM2FiGQjm87p5HsrzxtvILb4YgyC7YIFgY5YJiy1GkuaaFLGd9s3AI4EbdcI+nWTVH+v2HQE2N11tygzN4mf70RZDuE6FfkqNRYVSMhhCBdy/lGpC+TN3t8g+cOZHtuuabDrANI+1aO+KfGoGxc+1PICWRCDuUhvCAntZj8GXrsR2Hb/3uo/SMkUtodlzKv9shyRTNjd4R4CkfMIY9d/AV/nEeFoh4E35MRy1m0wAgAie75vurqm0V3BhXGzFJCyhn2eAQF0garhSJ8RVRzBibgt5fH45TbVn3UbfE72g=
  on:
    branch: master
env:
  global:
  - secure: UqidEwT1DkCfU4iDVMPdMI1nbtXqdaEyMM7xlKMfKruj2He10e4ThLFrLyCMAQ9yj5NtmZ7tlTkvzGxAZqB3BB43j3DGP2w18TzCncuSyJGQKylfT2hNf7KhmVkFhQor20eJB7I//4cRe5JQpmPaF3QQLEsX3X4Kv21Ge7DRTcHbDvgco5YclrBmbFkA2h1iHkrvMzcW1rFvfNjNkHOunbr0eJh6MmffV75MZgWcOIvM+fuelq48rYf941KAt6y2pYEOBUDh0kqtxnRXX5WRzbYjpQAfnBNtVXokcXddZC/6VDW1skATig6XI3ADwiQ6ZZBeV2SWZSZNJKtUtNcJWthzuEj1mSZxJac80lgUoX8N9bttZp+W4UfYfqnThah6XN5TDwusLqHYrx1smwN4FWs1FlUj243kjG+IkDTq1whcXarl1oX32FbTRpyRcZ+hZh+pmULEujeG6K6ijcgciFeRYQv1TzTzqom2DFVeeSRhkuN47Qli2h2tJhgPdg5g1ZgX97vejHoGMMZChgLvMkAWW1cjw+xy5WIeqgpSi1E+UzslQna1pbHrVkJJLMk5gFQEK5CDre547mD3/w/xfT9YGKB2T9DYBHeKI4mUQ56IQWTPOMra+DeXl0J6D+OAneoDXzC0izsENHzN5VXZSRm+HndlRw7hhbxcbl1BckI=
  - secure: KvZgbiPhSGKipjFb6SJtuhQJ69HSpn/EneU/6hrktvqrVyhVveise5nZsS106H5mvPNJXC0LiCTfRp0Cl19x56mU3FV6oRUWyunADuqNEP7dxOgYQDk83WXne7DIBEtQE6AyHg/ObcNzAn3kgEIBKykUwmnEqOU9xlQ6RLjafKTxXUhWiVo2xwzoSUZGSi4BFtR0+zSuwGJZ6uaSgAZHlBt+C17GmfVPsUXV0xrqM/ygWM1PcZYChUVvolSHLf1kFcquxHqRIBfs0j0SVlu3Vtev2+N+YStZnbGn5azpmT/Cm8N2iDN8YExLJVs1/gCdY0rRJ3fdDf4jxxtsNVYbXSSIKiEPAYbuqxNo+Gn4IlQhbt1oUIMPxGY0u5PZaezUwTyMrO3aW9UGj61b8n8HIQbKK90YN1yu+8bQtKgSjewPv2nOD/A3yQFjRxWqgzQbx3EEybxi+Fnl8e8jNipGGSlqn0T0BJ8CG4WYI93inBzxMAXNCDhGj9aD7qd7cTzpSSpm+fnmZTUDqYzlS+IAsZuqYUjfa+XvDs4gB0IzDH8ueIIpk4Jpf9sgEec1SLBKu5fv0H5/J1+OAlQsok1dg0MAkka54o7P9t+Grw8p2kYLAJLmf+dC/ef39uVJ7QRthnwvra1vZazfDO8Ytl9oP+3Az/RajmSn59h02XVUhTw=