language: node_js
node_js:
- '8'
dist: trusty
sudo: false
install:
- npm install
script:
- npm run code-check
- npm run build
- npm run test
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: MtJO84aDPPNOTD8PbqXYBAnQl47hk5N6LB4VBnC6MsankJR/AyeSsbSLJbo7hXsvC8l7yEIvcTqa3RO36Su1Yz6N41l/GGYtm+9LTZCqQ3ndvkFcKcEZYiA+ryX3PCngSUHgR+JMncE91dFFKqd+b59XKLtB/D7WA8xWpmPAuCjVZhdxMsCw6t4TltAgjUMQ8PfwbdBX7KZqfV2wUaf3l2U6xU9aDX+QrRDS3BuWj9DkULg9PzKlW4KItjkdZFaqcspRQ4L444SLEE55C5ayDP1ivmlmPRN5b1KhDmw+HQvwZOaTVE7TGKBcMoBMtCIqYFDDE2kkk2ndREQjDY9KpMewbMU4989lv66p4Svqr96py1K5YYsBCcot4W8Luk0InzqvFiie/5pAk8unoaVN7ggYJKU1+gUKnyDuWiGSGEhgkLzGjij8eqBL8ZjG5xXc+uDUcNrIef2RtT874FnfYaWpEfUpVP1NL28ZbX0wipC5sYFRhpNX8rHLGbf8a+kcbhn89CGBCOUnUTUwUhOGeK/Su7WI+3jWq7VAaSRoAqIixFirrotHzQ9t5AXzZHy/7eoR+inPqFBD98tqR+CYunYGp6I5oCiGUZ2xPD822rY4VbDksPUGE8ySLDF/FZQ2Nn7ZY4tGWuSTldK9DVKYmRs4pRVmppKz+X8GatgUhHE=
  on:
    branch: master
env:
  global:
  - secure: UqidEwT1DkCfU4iDVMPdMI1nbtXqdaEyMM7xlKMfKruj2He10e4ThLFrLyCMAQ9yj5NtmZ7tlTkvzGxAZqB3BB43j3DGP2w18TzCncuSyJGQKylfT2hNf7KhmVkFhQor20eJB7I//4cRe5JQpmPaF3QQLEsX3X4Kv21Ge7DRTcHbDvgco5YclrBmbFkA2h1iHkrvMzcW1rFvfNjNkHOunbr0eJh6MmffV75MZgWcOIvM+fuelq48rYf941KAt6y2pYEOBUDh0kqtxnRXX5WRzbYjpQAfnBNtVXokcXddZC/6VDW1skATig6XI3ADwiQ6ZZBeV2SWZSZNJKtUtNcJWthzuEj1mSZxJac80lgUoX8N9bttZp+W4UfYfqnThah6XN5TDwusLqHYrx1smwN4FWs1FlUj243kjG+IkDTq1whcXarl1oX32FbTRpyRcZ+hZh+pmULEujeG6K6ijcgciFeRYQv1TzTzqom2DFVeeSRhkuN47Qli2h2tJhgPdg5g1ZgX97vejHoGMMZChgLvMkAWW1cjw+xy5WIeqgpSi1E+UzslQna1pbHrVkJJLMk5gFQEK5CDre547mD3/w/xfT9YGKB2T9DYBHeKI4mUQ56IQWTPOMra+DeXl0J6D+OAneoDXzC0izsENHzN5VXZSRm+HndlRw7hhbxcbl1BckI=
  - secure: KvZgbiPhSGKipjFb6SJtuhQJ69HSpn/EneU/6hrktvqrVyhVveise5nZsS106H5mvPNJXC0LiCTfRp0Cl19x56mU3FV6oRUWyunADuqNEP7dxOgYQDk83WXne7DIBEtQE6AyHg/ObcNzAn3kgEIBKykUwmnEqOU9xlQ6RLjafKTxXUhWiVo2xwzoSUZGSi4BFtR0+zSuwGJZ6uaSgAZHlBt+C17GmfVPsUXV0xrqM/ygWM1PcZYChUVvolSHLf1kFcquxHqRIBfs0j0SVlu3Vtev2+N+YStZnbGn5azpmT/Cm8N2iDN8YExLJVs1/gCdY0rRJ3fdDf4jxxtsNVYbXSSIKiEPAYbuqxNo+Gn4IlQhbt1oUIMPxGY0u5PZaezUwTyMrO3aW9UGj61b8n8HIQbKK90YN1yu+8bQtKgSjewPv2nOD/A3yQFjRxWqgzQbx3EEybxi+Fnl8e8jNipGGSlqn0T0BJ8CG4WYI93inBzxMAXNCDhGj9aD7qd7cTzpSSpm+fnmZTUDqYzlS+IAsZuqYUjfa+XvDs4gB0IzDH8ueIIpk4Jpf9sgEec1SLBKu5fv0H5/J1+OAlQsok1dg0MAkka54o7P9t+Grw8p2kYLAJLmf+dC/ef39uVJ7QRthnwvra1vZazfDO8Ytl9oP+3Az/RajmSn59h02XVUhTw=
